export const airportData = [
    { _id: 'AGX', code: 'AGX', label: 'Agatti Island' },
    { _id: 'AMD', code: 'AMD', label: 'Ahmedabad' },
    { _id: 'AJL', code: 'AJL', label: 'Aizawl Airport' },
    { _id: 'AKD', code: 'AKD', label: 'Akola' },
    { _id: 'IXV', code: 'IXV', label: 'Along' },
    { _id: 'LKO', code: 'LKO', label: 'Amausi' },
    { _id: 'LUH', code: 'LUH', label: 'Amritsar' },
    { _id: 'LUH', code: 'LUH', label: 'Amritsar' },
    { _id: 'MAA', code: 'MAA', label: 'Chennai International' },
    { _id: 'BOM', code: 'BOM', label: 'Mumbai - Chhatrapati Shivaji International Airport' },
    { _id: 'IXR', code: 'IXR', label: 'Ranchi - Birsa Munda International Airport' },
    { _id: 'BLR', code: 'BLR', label: 'Bengaluru International Airport' },
    { _id: 'BHU', code: 'BHU', label: 'Bhavnagar Airport' },
    { _id: 'GOI', code: 'GOI', label: 'Goa- Dabolim Airport' },
    { _id: 'UDR', code: 'UDR', label: 'Udaipur- Dabok Airport' },
    { _id: 'DIU', code: 'DIU', label: 'Diu Airport' },
    { _id: 'HYD', code: 'HYD', label: 'Hyderabad Airport' },
    { _id: 'DEL', code: 'DEL', label: 'New Delhi - Indira Gandhi Airport' },
    { _id: 'PNQ', code: 'PNQ', label: 'Pune - Lohegaon Airport' },
    { _id: 'BHJ', code: 'BHJ', label: 'Bhuj - Rudra Mata Airport' },
    { _id: 'BDQ', code: 'BDQ', label: 'Vadodara Airport' },
    { _id: 'STV', code: 'STV', label: 'Surat Airport' },
    { _id: 'HEL', code: 'HEL', label: 'Helsinki Airport' },
    { _id: 'OUL', code: 'OUL', label: 'Oulu Airport' },
    { _id: 'HAN', code: 'HAN', label: 'Vietnam - Noi Bai Airport' },
    { _id: 'SGN', code: 'SGN', label: 'Vietnam - Tan Son Nhat Airport' },
];

// { _id: 'ahm', name: 'Ahmedabad', code: 'AMD' },
// { _id: 'bom', name: 'Mumbai', code: 'BOM' },
// { _id: 'idr', name: 'Indore', code: 'IDR' },
// { _id: 'maa', name: 'Chennai', code: 'MAA' },
// { _id: 'del', name: 'New Delhi', code: 'DEL' },
// { _id: 'goi', name: 'Goa - Dabolim', code: 'GOI' },